# Generated by Django 2.2.2 on 2019-06-17 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
