# Generated by Django 2.2.2 on 2019-06-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_auto_20190617_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='date',
        ),
    ]
