# Generated by Django 2.2.2 on 2019-06-17 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_auto_20190617_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 23, 20, 38, 313563)),
        ),
    ]
