# Generated by Django 2.2.2 on 2019-06-17 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0007_auto_20190617_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 23, 22, 50, 622115, tzinfo=utc)),
        ),
    ]
